name = "describe-test-broken-vitest2"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
logpush = true
routes = ["describe-test-broken-vitest2.example.com/*"]

[placement]
mode = "smart"

[vars]
NAME = "describe-test-broken-vitest2"
ENVIRONMENT = "production"
AXIOM_DATASET = "workers"
AXIOM_DATASET_OTEL = "workers-otel"

